services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"